name: Build and publish to Azure

on: [push]

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build --configuration Release ./app-api
  deploy:
    needs: build
    name: Deploy App
    runs-on: ubuntu-latest
    
    steps:
    - name: deploy to azure web app
      uses: azure/appservice-actions/webapp@master
      with: 
        app-name: StudentAppA
        publish-profile: ${{ secrets.AZURE }}    
